name: lab_9_1
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  equatable: ^2.0.7
  flutter_bloc: ^9.1.0
  json_annotation: ^4.9.0
  flutter_screenutil: ^5.9.3
  retrofit_generator: ^9.1.9
  retrofit: ^4.0.1
  dio: ^5.8.0+1
  dio_web_adapter: ^2.1.1
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^10.0.0-beta.4
  bloc: 9.0.0
  cupertino_icons: ^1.0.8
  meta: ^1.16.0

dev_dependencies:
  json_serializable: ^6.9.4
  build_runner: ^2.4.15
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
